name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  dotnet_version: 6.0.x

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Code format
      run: dotnet csharpier --check src

  linux:
    runs-on: ubuntu-latest
    needs: code
    steps:
    - name: Install build tools
      run: sudo apt-get install -y cmake ninja-build
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install local deps
      run: |
        chmod +x ./install-deps.sh
        ./install-deps.sh
    - name: Setup native project
      run: cmake nativesrc --preset linux-debug
    - name: Setup PFFFT 
      run: cmake nativesrc/pffft/ --preset linux-release
    - name: Build PFFFT
      run: cmake --build nativesrc/pffft/out/build/linux-release
    - name: Build native code
      run: cmake --build nativesrc/out/build/linux-debug
    - name: Build
      run: dotnet build src -c LinuxDebug
    - name: Test
      run: dotnet test src --no-build --verbosity normal -c LinuxDebug

  windows:
    runs-on: windows-latest
    needs: code
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      shell: pwsh
      run: .\install-deps.ps1
    - name: Setup native project
      run: cmake nativesrc --preset x64-debug
    - name: Build native code
      run: cmake --build nativesrc\out\build\x64-debug
    - name: Setup PFFFT 
      run: cmake .\nativesrc\pffft\ --preset x64-release
    - name: Build PFFFT
      run: cmake --build nativesrc\pffft\out\build\x64-release --config Release
    - name: Archive Native artifacts
      uses: actions/upload-artifact@v3
      with:
        name: native-${{ matrix.os }}-${{ matrix.version }}
        path: |
          nativesrc\pffft\out\build\x64-release
          nativesrc\out\build\x64-debug
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore -c Debug
    - name: Test
      run: dotnet test src --no-build --verbosity normal -c Debug
